<?php

/**
 * Processwire and Bootstrap 3 templated footer
 *
 */

?>

</body>
<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
<!-- fileblock:js allscripts -->
<script src="/site/templates/assets/js/combined-libs.min.js"></script>
<script src="/site/templates/assets/js/custom-bootstrap.min.js"></script>
<script src="/site/templates/assets/js/default.min.js"></script>
<!-- endfileblock -->
</html>
